add confirm message to function drop database to enhance that function

diff --git a/maindbms b/maindbms
--- a/maindbms
+++ b/maindbms
@@ -19,10 +19,10 @@ ls "$DB_ROOT"
 }
 
 
-function drop_db() {
-read -p "Enter database name: " db
-rm -r "$DB_ROOT/$db" 2>/dev/null && echo "Database deleted" || echo "Database not found"
-}
+#function drop_db() {
+#read -p "Enter database name: " db
+#rm -r "$DB_ROOT/$db" 2>/dev/null && echo "Database deleted" || echo "Database not found"
+}#
 
 function connect_db() {
     read -p "Enter DB name: " dbname
@@ -36,7 +36,34 @@ function connect_db() {
     fi
 }
 
+function drop_db() {
+    read -p "Enter database name: " db
 
+    if [ -z "$db" ]; then
+        echo "Invalid name!"
+        return
+    fi
+
+    if [ ! -d "$DB_ROOT/$db" ]; then
+        echo "Database not found"
+        return
+    fi
+
+    read -p "Are you sure you want to delete '$db'? (y/n): " confirm
+
+    case $confirm in
+        y|Y)
+            rm -r "$DB_ROOT/$db"
+            echo "Database deleted"
+            ;;
+        n|N)
+            echo "Operation cancelled"
+            ;;
+        *)
+            echo "Invalid choice"
+            ;;
+    esac
+}
 function main_menu() {
     select choice in "Create DB" "List DB"  "Connect DB" "Drop DB" "Exit"
     do
